# -*- coding: utf-8 -*-
"""day3_elevate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiWiH_XEmuiNSdaDWDTQDrndxqgls6Jc
"""

import pandas as pd
df=pd.read_csv('Housing.csv')
df.info()

df.sample(5)

!pip install -U ydata-profiling

from ydata_profiling import ProfileReport
prof=ProfileReport(df,title='EDA ON HOUSING DATASET',explorative=True)
prof.to_file("output.html")



X=df.iloc[:,[1]]

Y=df.iloc[:,[0]]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

from sklearn.linear_model import LinearRegression
m1=LinearRegression()
m1.fit(X_train,y_train)

y_pred=m1.predict(X_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import numpy as np
import matplotlib.pyplot as plt
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))
print("R2 Score",r2_score(y_test,y_pred))

plt.scatter(df['area'],df['price'])
plt.plot(X_train,m1.predict(X_train),color='red')
plt.xlabel('area')
plt.ylabel('price')

m1.coef_

m1.intercept_